<a href="https://colab.research.google.com/github/sumanbhattarai58/Deeplearning_with_pytorch/blob/main/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Creating neural network with 6 inputs, and a single neuron with one output.

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out= self.sigmoid(out)

    return(out)

In [ ]:
#create dataset
features = torch.rand(10,6)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4777],
        [0.4593],
        [0.5109],
        [0.4683],
        [0.4949],
        [0.4329],
        [0.5925],
        [0.4568],
        [0.5745],
        [0.5997]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[-0.3745,  0.0207,  0.1507,  0.2874,  0.3820,  0.0197]],
       requires_grad=True)

In [ ]:
#show model bias
model.linear.bias

Parameter containing:
tensor([-0.2201], requires_grad=True)

In [ ]:
pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,6))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   7
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 7
Trainable params: 7
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

2. Creating neural network with 6 inputs, no. of hidden layer 1 with 4 neurons and single output.

In [ ]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,4)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(4,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return(out)



In [ ]:
#create dataset
features = torch.rand(10,6)
print(features)

tensor([[0.9862, 0.8410, 0.6393, 0.3449, 0.5551, 0.5356],
        [0.2694, 0.8639, 0.5808, 0.7592, 0.5619, 0.8644],
        [0.5796, 0.0340, 0.1239, 0.5967, 0.2745, 0.2891],
        [0.5163, 0.6670, 0.6256, 0.1597, 0.7671, 0.7826],
        [0.2209, 0.5831, 0.8235, 0.6004, 0.5993, 0.3317],
        [0.7346, 0.7787, 0.3867, 0.5009, 0.5670, 0.7214],
        [0.7528, 0.7892, 0.0282, 0.7832, 0.9858, 0.0854],
        [0.2580, 0.5435, 0.2944, 0.0146, 0.9556, 0.7241],
        [0.8351, 0.7526, 0.7917, 0.4599, 0.0886, 0.4241],
        [0.8199, 0.3934, 0.9218, 0.7622, 0.7609, 0.5844]])


In [ ]:
#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.5703],
        [0.5575],
        [0.5744],
        [0.4990],
        [0.5522],
        [0.5615],
        [0.6160],
        [0.4640],
        [0.5951],
        [0.5840]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-3.1601e-01, -3.1600e-01, -2.1083e-01, -9.7364e-02,  1.5867e-01,
         -7.7424e-02],
        [ 1.1312e-01, -6.7253e-02, -2.8724e-01,  2.9054e-01, -1.8335e-01,
         -1.8399e-01],
        [ 1.1589e-01, -3.0787e-04,  1.7040e-01,  4.0168e-01, -4.4994e-02,
         -1.1795e-01],
        [ 3.3212e-01,  3.5186e-01,  6.9003e-02,  3.6132e-01, -1.1434e-01,
         -1.6891e-01]], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,6))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 4]                   28
├─ReLU: 1-2                              [10, 4]                   --
├─Linear: 1-3                            [10, 1]                   5
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
#Use of sequential
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.network = nn.Sequential(
       nn.Linear(num_features,4),
       nn.ReLU(),
       nn.Linear(4,1),
       nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)


    return(out)

