<a href="https://colab.research.google.com/github/sumanbhattarai58/Deeplearning_with_pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("gpu not available")

GPU is available
using GPU: Tesla T4


 Ways of creating a **tensor**

In [ ]:
#using empty
a = torch.empty(3,3)
print(a)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.4836e-10, 2.5668e-09, 5.2946e+22]])


In [ ]:
print(type(a))

<class 'torch.Tensor'>


In [ ]:
#using zeros
torch.zeros(3,3)          #useful while initialising biases

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(3,3)       #rand produces random number each time, so not reproducible

tensor([[0.8820, 0.0628, 0.3655],
        [0.3568, 0.1110, 0.0011],
        [0.6876, 0.9372, 0.3602]])

In [ ]:
#manual seed
#(makes use of rand producing same random number every time which makes code reproducible)
torch.manual_seed(50)
torch.rand(3,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442],
        [0.4605, 0.4877, 0.5927]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

**Tensor** **Shapes**

In [ ]:
x= torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [ ]:
x.shape

torch.Size([2, 3])

If you want to create tensors of the same size as 'x', then you can use empty,ones,zeros as:

In [ ]:
torch.empty_like(x)

tensor([[              0,       145910432,       116232304],
        [135159154609120,               0,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x)  #creates error

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
#solution of rand
torch.rand_like(x,dtype=torch.float32)

tensor([[0.9634, 0.1230, 0.4048],
        [0.4985, 0.9987, 0.6049]])

Torch Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
y=torch.tensor([2.0,3,4])
print(y)
y.dtype

tensor([2., 3., 4.])


torch.float32

In [ ]:
y=torch.tensor([2.0,3,4], dtype=torch.int32)
y

tensor([2, 3, 4], dtype=torch.int32)

In [ ]:
#changing datatype
a=torch.tensor([1,2,3])
a=a.to(torch.float32)
print(a)
a.dtype

tensor([1., 2., 3.])


torch.float32

Operations

In [ ]:
torch.sum(a)

tensor(6.)

In [ ]:
torch.mean(a)

tensor(2.)

Matrix Multiplication

In [ ]:
c=torch.randint(size=(2,3),low=1,high=9)
d=torch.randint(size=(3,2),low=1,high=9)
print(c)
print(d)

tensor([[3, 8, 8],
        [5, 7, 4]])
tensor([[5, 4],
        [3, 3],
        [7, 5]])


In [ ]:
#matrix multiplication
torch.matmul(c,d)

tensor([[95, 76],
        [74, 61]])

In [ ]:
#Transpose
torch.transpose(d,0,1)

tensor([[5, 3, 7],
        [4, 3, 5]])

In [ ]:
torch.transpose(d,1,0)

tensor([[5, 3, 7],
        [4, 3, 5]])

In [ ]:
#sum along the column
torch.sum(d,dim=0)

tensor([15, 12])

In [ ]:
#sum along the rows
torch.sum(d,dim=1)

tensor([ 9,  6, 12])

Inplace operations

In [ ]:
e=torch.randint(size=(3,2),low=1,high=9)
f=torch.randint(size=(3,2),low=1,high=9)
print(e,f)

tensor([[1, 7],
        [4, 7],
        [4, 3]]) tensor([[8, 7],
        [2, 4],
        [4, 3]])


In [ ]:
e.add_(f)

tensor([[ 9, 14],
        [ 6, 11],
        [ 8,  6]])

In [ ]:
e

tensor([[ 9, 14],
        [ 6, 11],
        [ 8,  6]])

sum of e and f is stored in e and doesnt occupy any other extra memory.

Tensor Operations on gpu

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device= torch.device('cuda')

In [ ]:
#creating a new tensor
torch.rand(2,3,device=device )

tensor([[0.3146, 0.1458, 0.3482],
        [0.9447, 0.1015, 0.8101]], device='cuda:0')

In [ ]:
#moving an existing tensor to gpu
d

tensor([[4, 8],
        [2, 6],
        [3, 2]])

In [ ]:
d=d.to(device)
d

tensor([[4, 8],
        [2, 6],
        [3, 2]], device='cuda:0')